# (c) Copyright Riverlane 2020-2026. All rights reserved.
import itertools
from collections.abc import Callable, Mapping, Sequence
from concurrent.futures import ProcessPoolExecutor
from copy import deepcopy

import numpy as np
import numpy.typing as npt
from deltakit_circuit._circuit import Circuit
from deltakit_decode._mwpm_decoder import PyMatchingDecoder
from deltakit_decode.analysis._matching_decoder_managers import StimDecoderManager
from tqdm import tqdm

from deltakit_explorer.analysis.error_budget._decoding import (
    _CorrelatedMatchingDecoder,
    _SeededStimDecoderManager,
)
from deltakit_explorer.analysis.error_budget._memory import (
    MemoryGenerator,
    get_rotated_surface_code_memory_circuit,
)


def _point_ids(xi: npt.NDArray[np.floating]) -> list[int]:
    """Assign stable IDs to exact vectors, sharing IDs for replicated points.

    Args:
        xi: Noise vectors stored as columns.

    Returns:
        One exact-vector ID per column, in input order.
    """
    registry: dict[tuple[float, ...], int] = {}
    return [registry.setdefault(tuple(vector), len(registry)) for vector in xi.T]


def _seed_stream(seed: int | None, stream: int) -> np.random.SeedSequence | None:
    """Separate pilot (0) and production (1) streams without consuming either.

    Args:
        seed: Optional root seed.
        stream: Independent stream identifier.

    Returns:
        A seed sequence for the requested stream, or None for unseeded sampling.
    """
    return None if seed is None else np.random.SeedSequence(seed, spawn_key=(stream,))


def _generate_surface_code_memory_decoder_manager(
    distance: int,
    num_rounds: int,
    noise_model: Callable[[Circuit, npt.NDArray[np.floating]], Circuit],
    noise_parameters: npt.NDArray[np.floating],
    memory_generator: MemoryGenerator,
    noise_parameter_names: Sequence[str],
    point_id: int | None = None,
    enable_correlations: bool = False,
    seed: int | None = None,
    batch_size: int = 10_000,
) -> StimDecoderManager:
    """Generate a decoder manager with a rotated planar code memory experiment.

    Args:
        distance (int): distance of the rotated planar code memory experiment that
            should be generated by this function.
        num_rounds (int): number of stabilizer measurement rounds of the memory
            experiment generated by this function.
        noise_model (Callable[[Circuit, npt.NDArray[np.floating]], Circuit]): a callable
            adding noise to the provided circuit, according to the parameters provided
            in the second argument.
        noise_parameters: parameters for the ``noise_model`` callable representing the
            noise strength.
        memory_generator: a callable that is able to generate memory experiments from a
            given distance and number of rounds.
        noise_parameter_names: if provided, human-readable names for each of the
            provided ``noise_parameters``.
        point_id: Exact-vector identity to retain in task metadata.
        enable_correlations: Use the complete DEM for correlated matching.
        seed: Independent seed for this sampling task.
        batch_size: Internal sampling batch size.

    Returns:
        a decoder manager that can then be run using ``RunAllAnalysisEngine``.
    """
    circuit = deepcopy(memory_generator(distance, num_rounds))
    noisy_circuit = noise_model(circuit, noise_parameters.copy())
    decoder_type = (
        _CorrelatedMatchingDecoder if enable_correlations else PyMatchingDecoder
    )
    decoder, decoder_circuit = decoder_type.construct_decoder_and_stim_circuit(
        noisy_circuit
    )
    metadata = {
        "distance": distance,
        "num_rounds": num_rounds,
        **{
            f"noise_{name}": p
            for name, p in zip(noise_parameter_names, noise_parameters, strict=True)
        },
    }
    if point_id is not None:
        metadata["point_id"] = point_id
    if seed is not None:
        metadata["seed"] = seed

    manager_type = _SeededStimDecoderManager if seed is not None else StimDecoderManager
    return manager_type(
        decoder_circuit,
        decoder,
        metadata=metadata,
        seed=seed,
        batch_size=batch_size,
    )


def _generate_surface_code_memory_decoder_manager_wrapper(
    data: tuple[
        int,
        int,
        Callable[[Circuit, npt.NDArray[np.floating]], Circuit],
        npt.NDArray[np.floating],
        MemoryGenerator,
        Sequence[str],
        int,
        bool,
        int | None,
        int,
    ],
) -> StimDecoderManager:
    return _generate_surface_code_memory_decoder_manager(*data)


def generate_decoder_managers_for_lambda(
    xi: npt.NDArray[np.floating],
    noise_model: Callable[[Circuit, npt.NDArray[np.floating]], Circuit],
    num_rounds_by_distances: Mapping[int, Sequence[int]],
    max_workers: int = 1,
    memory_generator: MemoryGenerator = get_rotated_surface_code_memory_circuit,
    noise_parameter_names: Sequence[str] | None = None,
    *,
    point_ids: Sequence[int] | None = None,
    enable_correlations: bool = False,
    seed: int | np.random.SeedSequence | None = None,
    batch_size: int = 10_000,
) -> list[StimDecoderManager]:
    """Generate several decoder managers from the provided arguments for a rotated
    planar code memory experiment.

    This function should be used to generate in one call a description of all the
    sampling tasks that should be done in order to estimate the value of Λ on the
    provided noise parameters ``xi``.

    Note:
        Generating the tasks might be a long process, hence the presence of the
        ``max_worker`` parameter.

    Warning:
        This function will generate ``len(num_rounds) * len(distances) *
        numpy.prod(xi.shape[1:])`` sampling tasks. That quantity
        might grow quickly, so try to avoid providing too many entries in ``distances``
        and ``num_rounds`` except if you really need it.

    Args:
        xi (npt.NDArray[numpy.floating]): an array of shape ``(m, n)``, where ``m`` is
            the number of noise parameters needed by ``noise_model`` and ``n`` the
            number of points to evaluate Λ on.
        noise_model (Callable[[Circuit, npt.NDArray[np.floating]], Circuit]): a callable
            adding noise to the provided circuit, according to the parameters provided.
        num_rounds_by_distances (Mapping[int, Sequence[int]]): the different number of
            rounds that will be used to estimate the logical error-rate per round for
            each code distance. As a rule of thumb, at least ``4`` entries should be
            provided and the maximum number of rounds should, if possible, give a
            logical error-rate above ``0.2`` for the largest distance and a logical
            error-rate below ``0.45`` for the smallest distance. You will not be able to
            check those thresholds everytime, but the standard errors computed will be
            lower if they are verified.
        max_workers (int): if provided, the number of parallel processes that are used
            to generate the sampling tasks. If not, default to ``1``.
        memory_generator: a callable that is able to generate memory experiments from a
            given distance and number of rounds.
        noise_parameter_names: if provided, human-readable names for each of the
            provided ``noise_parameters``. Defaults to the noise parameter index (i.e.,
            "0", "1", ...).
        point_ids: IDs for columns of xi. By default, exact duplicate vectors share
            an ID but retain separate sampling tasks and independent seeds.
        enable_correlations: Enable correlated matching in construction and decoding.
        seed: Seed or call-local seed stream from which to spawn distinct task seeds.
        batch_size: Internal sampling batch size for each manager.

    Returns:
        a list of decoder managers that can then be run using ``RunAllAnalysisEngine``.
    """
    if noise_parameter_names is None:
        noise_parameter_names = [str(i) for i in range(xi.shape[0])]
    if point_ids is None:
        point_ids = _point_ids(xi)
    if len(point_ids) != xi.shape[1]:
        msg = "point_ids must contain one ID per sampling column."
        raise ValueError(msg)
    # 0. Transposing to be able to iterate on different values.
    noise_parameters = xi.T
    # 1. Check input parameters
    if max_workers <= 0:
        msg = f"Cannot have less than one worker. Asked for {max_workers} workers."
        raise ValueError(msg)
    # 2. Build an iterator on all the parameters we need to provide to the generation
    # method.
    total_circuits = (
        sum(len(num_rounds) for num_rounds in num_rounds_by_distances.values())
        * noise_parameters.shape[0]
    )
    seed_sequence = (
        seed
        if isinstance(seed, np.random.SeedSequence)
        else (np.random.SeedSequence(seed) if seed is not None else None)
    )
    task_seeds = iter(
        [
            int(child.generate_state(1, dtype=np.uint64)[0])
            for child in seed_sequence.spawn(total_circuits)
        ]
        if seed_sequence is not None
        else [None] * total_circuits
    )
    # (distance: int, num_rounds: int)
    distance_and_rounds_iterator = itertools.chain.from_iterable(
        zip(itertools.repeat(d, len(rounds)), rounds, strict=True)
        for d, rounds in num_rounds_by_distances.items()
    )
    parameters_iterator = (
        (
            distance,
            num_rounds,
            noise_model,
            noise_parameter,
            memory_generator,
            noise_parameter_names,
            point_id,
            enable_correlations,
            next(task_seeds),
            batch_size,
        )
        for ((distance, num_rounds), (point_id, noise_parameter)) in itertools.product(
            distance_and_rounds_iterator, zip(point_ids, noise_parameters, strict=True)
        )
    )
    # 3. Generate the decoder managers
    decoder_managers: list[StimDecoderManager] = []
    if max_workers == 1:
        for parameters in tqdm(
            parameters_iterator,
            total=total_circuits,
            desc="Generating quantum circuits",
        ):
            decoder_managers.append(
                _generate_surface_code_memory_decoder_manager(*parameters)
            )
        return decoder_managers
    # Else, we might use several workers
    with ProcessPoolExecutor(max_workers=max_workers) as pool:
        return list(
            tqdm(
                iterable=pool.map(
                    _generate_surface_code_memory_decoder_manager_wrapper,
                    parameters_iterator,
                ),
                total=total_circuits,
                desc="Generating quantum circuits",
            )
        )
